### ISSUE TITLE
Low speeds and high ping

### ISSUE THREAD

**Issue by rinukkusu** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#20]
I've set this up yesterday after the fix from #17 came in with the dashboard example json from this repository. But I'm not sure what to make of the results:
![grafik](https://user-images.githubusercontent.com/804848/51817939-4010e580-22cd-11e9-8a59-28b51b6b80c7.png)

I have 300mbps down and 30mbps up and a regular test on speedtest.net seems to confirm that:
![grafik](https://user-images.githubusercontent.com/804848/51818181-2ae88680-22ce-11e9-8af5-17ca2c2c6d1a.png)

Does anyone have an idea what's going on?

**Comment by barrycarey** [comment]
That would make me think it's selecting a server that is not very close to you. Are you manually setting a server or allowing it to pick on it's own?

**Comment by rinukkusu** [comment]
I picked the `config.ini` from this repository - only change I made were the InfluxDB settings. 😕 
Do you know where I should look for logs or anything? Maybe even try and run the `speedtest-cli` myself inside the docker container?

**Comment by kubax** [comment]
@rinukkusu 
could also be possible that the dashboard you used is set to the wrong datatype when displaying the info...

As a reference see these screenshots from my panel (I'd share the complete panel, but it also containes data from my router and some manual ping tests wich would not work on your setup)

![bildschirmfoto von 2019-01-29 16-32-17](https://user-images.githubusercontent.com/1083100/51919508-d7685c80-23e3-11e9-8c74-a5da65169a50.png)
![bildschirmfoto von 2019-01-29 16-33-19 - 1](https://user-images.githubusercontent.com/1083100/51919514-dafbe380-23e3-11e9-9426-06aeedb8cbb2.png)
![bildschirmfoto von 2019-01-29 16-33-39](https://user-images.githubusercontent.com/1083100/51919526-e2bb8800-23e3-11e9-94a9-27c3ce057c6f.png)

**Comment by barrycarey** [comment]
Does the console output from the script match the speeds it shows in Grafana?  After a speed test completes it should show you the results in the console.

**Comment by rinukkusu** [comment]
Yes, in the docker container I get the same results:

```
# speedtest-cli
Retrieving speedtest.net configuration...
Testing from UPC Austria (x.x.x.x)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Telemach Rotovz d.d. (Maribor) [70.53 km]: 246.193 ms
Testing download speed................................................................................
Download: 0.15 Mbit/s
Testing upload speed......................................................................................................
Upload: 0.21 Mbit/s
```
On my local machine I get only slightly better results, when running the python script:

```
max@minzblatt ~ $ speedtest-cli
Retrieving speedtest.net configuration...
Testing from UPC Austria (x.x.x.x)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Citycom Telekommunikation GmbH (Graz) [10.73 km]: 144.289 ms
Testing download speed................................................................................
Download: 4.06 Mbit/s
Testing upload speed......................................................................................................
Upload: 3.88 Mbit/s
```

Which means there is something wrong with that script, I suppose, since I get good test results on the speedtest site itself ... :smile:

**Comment by barrycarey** [comment]
Try manually setting a different server. Speedtest-CLI has a flag to list all the servers.  You can get an ID from there and set it in the config for this tool.

**Comment by rinukkusu** [comment]
`Citycom Telekommunikation GmbH (Graz)` is already the nearest server from which I get the good 300Mbps on the web version, but only 4Mbps in the CLI version. So I will check with the issues on the `speedtest-cli` repo. Thanks for your help!

**Comment by tb205gti** [comment]
Did you ever fix this? After messing wit hPython versions I get 4MBps in Grafana - but running my providers speedtest (or speedtest.net) I see the normal upload speed.

Download is not affected, but upload is way off. Tried multiple servers, and no specifed server - all are the same. speedtest-cli shows me the right speeds.

EDIT: tried the speedtest-cli from the docker image - there I get low upload. Updated from 2.0.2 to latest - now it seems I get the right speeds..
