### ISSUE TITLE
Container fails to start if server is offline

### ISSUE THREAD

**Issue by skylord123** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#21]
I was having issues getting the container to start recently and I notice that if one of the servers listed in the config fails to respond it will crash the container. I have two servers listed and only one is responding atm (other is possibly down due to maintenance).

This is my log:
```
Loading Configuration File config.ini
Configuration Successfully Loaded
2019-01-29 02:33:53,338 - ERROR: No matched servers: [5780]

Traceback (most recent call last):
File "/src/influxspeedtest.py", line 8, in <module>
collector.run()
File "/src/influxspeedtest/InfluxdbSpeedtest.py", line 168, in run
self.run_speed_test(server)
File "/src/influxspeedtest/InfluxdbSpeedtest.py", line 125, in run_speed_test
self.speedtest.download()
File "/usr/local/lib/python3.7/site-packages/speedtest.py", line 1449, in download
(os.path.dirname(self.best['url']), size, size))
File "/usr/local/lib/python3.7/site-packages/speedtest.py", line 1045, in best
'get_best_server not called or not able to determine best '
speedtest.SpeedtestMissingBestServer: get_best_server not called or not able to determine best server
```

Needs to be fixed so it keeps running and just retries the server (either make it retry the next time interval or every X minutes -- possibly make it configurable).

**Comment by barrycarey** [comment]
Try it now.  It should be fixed.

**Comment by skylord123** [comment]
I'm using the atribe docker image. Is there any reason why this repo doesn't have the docker image for it in dockerhub? I had to do this PR to get the changes into the atribe repo so I can actually test this:

https://github.com/atribe/Speedtest-for-InfluxDB-and-Grafana/pull/5

**Comment by barrycarey** [comment]
I've never messed around with Docker.  All the Docker support for my projects was added by other people. 

I plan on playing with it this weekend and adding proper support

**Comment by barrycarey** [comment]
Docker image is now on my account and linked to this repo
