### ISSUE TITLE
change to more performant cli

### ISSUE THREAD

**Issue by wuast94** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#28]
Would it possible to change to this Speedtest-cli ? should be much more accurate.
https://github.com/taganaka/SpeedTest

Would be nice because the normal cli don't make sense for me:
vm on this server with win 10 and manually on web page: 398 down and 48 up
this container on same server: 146 down and 4 up.

**Comment by axipher** [comment]
I'm also having a limit of around 4 Mbps on the Upload through Docker on UnRaid, My Download is able to hit my ISP's 200 Mbps no problem, but not the Upload of 100 Mbps.  Ping is also coming in nicely around 7 ms to a local Speedtest Server in my city.

**Comment by wuast94** [comment]
I have written a script with the better cli to run a speedtest and write it to influxdb. I can share it the next days but haven't the time to build a container with it.

**Comment by axipher** [comment]
@wuast94 willing to test it if you need, I tried setting the current speedtest docker from this repo to anywhere from a single thread, to all 16 of my CPU, and it barely touches the CPU, and still maxes out at 4 Mbps.

**Comment by axipher** [comment]
Found a simple fox for this Docker, at least on UnRaid.  Open the Console for the Docker itself and just run the following command:

`pip install speedtest-cli --upgrade`

I got this information from the following page: https://www.howtoforge.com/tutorial/check-internet-speed-with-speedtest-cli-on-ubuntu/

After Upgrading, I went form results of 400 / 4 to 400 / 200 which matches my actual connection.

**Comment by atribe** [comment]
I can probably look at updating the docker container to have the newer version

**Comment by barrycarey** [comment]
I just linked this repo to my Docker Hub so it should keep updated.  The new version of speedtest-cli seems to fix this issue.
