### ISSUE TITLE
Doesn't allow http or https in url

### ISSUE THREAD

**Issue by douglasg14b** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#5]
my influx db is at `https://someserver.somedomain.com:8086`, if I use `https://someserver.somedomain.com` in the config it comes out as `//someserver.somedomain.com` after parsing.

**Comment by barrycarey** [comment]
U

**Comment by douglasg14b** [comment]
@barrycarey Is there a reason this was closed?

- Was it fixed?
- Is this being ignored
- Is this not reproduceable?
- Just cause?
...etc

**Comment by barrycarey** [comment]
Sorry, hadn't touched the repo in ages.  Was doing updates and cleaning up today. 

In the config put someserver.somedomain.com as the address.  No need for anything else.  The port is defined separately in the config.  The InfluxDB library takes care of the HTTP portion internally.
