### ISSUE TITLE
This script no longer works

### ISSUE THREAD

**Issue by samcro1967** [barrycarey/Speedtest-for-InfluxDB-and-Grafana#6]
Table is created in Influxdb, but no data is ever written.  Tried both the script and the containerized version and neither writes data to Influx.  No errors are generated.

**Comment by ricardocmello** [comment]
It is currently working on my Raspberry Pi. Downloaded it a couple of days ago and I'm running it directly from the .py file. Only thing I had to change was importing ConnectionError from requests.exceptions. After that, it was able to create the database and write data on it. 

Not sure about your issue though, sorry I can't help you. Just wanted to add this comment as I don't think the issue title reflects the actual problem.

**Comment by billimek** [comment]
Confirmed working for me too via docker image `atribe/speedtest-for-influxdb-and-grafana:latest`:

```shell
❯ k logs speedtest-578657894f-779fg | tail -6
[{'measurement': 'speed_test_results', 'fields': {'ping': 21.156, 'upload': 22748419.70990844, 'download': 173419667.052564}, 'tags': {'server': 'Speedtest.net'}}]
Written To Influx: [{'measurement': 'speed_test_results', 'fields': {'ping': 21.156, 'upload': 22748419.70990844, 'download': 173419667.052564}, 'tags': {'server': 'Speedtest.net'}}]
Download: 142126944.04031068
Upload: 22569890.170588937
[{'measurement': 'speed_test_results', 'fields': {'ping': 21.156, 'upload': 22569890.170588937, 'download': 142126944.04031068}, 'tags': {'server': 'Speedtest.net'}}]
Written To Influx: [{'measurement': 'speed_test_results', 'fields': {'ping': 21.156, 'upload': 22569890.170588937, 'download': 142126944.04031068}, 'tags': {'server': 'Speedtest.net'}}]
```

**Comment by atribe** [comment]
I had to run the container twice. It hung the first time on the database doesn't exist message, but upon a second run it worked with no problems.
